### ISSUE TITLE
bug: ReVanced Player keeps loading after 10 seconds of playback 

### ISSUE THREAD

**Issue by Andandrei13** [inotia00/ReVanced_Extended#141]
### Type

Error at runtime

### Application

Youtube ReVanced 18.01.36

### Bug description

While playing any video it loads the first 10 seconds then it buffers forever

### Steps to reproduce

Play any video. I have the latest vanced microg

### Relevant log output

```shell
-
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
This is a new type of buffering issue in the UK region

There is no perfect solution other than using a ROOT build or using a vpn

**Comment by Arkanu11** [comment]
@inotia00 this is not only in the UK region, it happens in Romania as well.
The playback is flawless when incognito mode is turned on or when you log out of the Google account. Any idea on why this would be connected to the identified user?

**Comment by inotia00** [comment]
> @inotia00 this is not only in the UK region, it happens in Romania as well. The playback is flawless when incognito mode is turned on or when you log out of the Google account. Any idea on why this would be connected to the identified user?

Google is currently blocking the ReVanced client for non-root users in some European regions
As of now, there is no clear solution other than using a root build or using a vpn to connect to a country other than Europe

**Comment by KPVADALIYA** [comment]
This is also happening in short

Short are starting from middle

**Comment by rohan-hopstack** [comment]
This is happening in India bangalore too

**Comment by kroimon** [comment]
Some analysis about the issue at https://github.com/microg/GmsCore/issues/1870.
Unfortunately no progress yet.

Started affecting my account in Germany a few days ago.

**Comment by Kiwiiizzz** [comment]
This is happening for me too and I live in California

**Comment by 999k999** [comment]
Brasil a mesma coisa ,carrega o vídeo ,passa 10 segundos e o vídeo fica em loop infinito.

**Comment by guisz1** [comment]
this is happening in brazil too

**Comment by Vactarian** [comment]
This is happening in Canada as well

**Comment by Andandrei13** [comment]
I have found out the problem, i changed the email account with a new email and the problem got solved. This might be a blacklist of accounts from google directly as they might notice the high consumption of content without ads,  so changing the email address will resolve the issue for an unknown period of time

**Comment by sliceanddice9** [comment]
> I have found out the problem, i changed the email account with a new email and the problem got solved. This might be a blacklist of accounts from google directly as they might notice the high consumption of content without ads, so changing the email address will resolve the issue for an unknown period of time

But that means you have to use a entirety new account to log in to YouTube right? Is there an easy and quick way to import all subscriptions from one account to another?

**Comment by iLagTooMuch** [comment]
Do the devs have any plans on fixing or bypassing this problem? Because of this I can't use ReVanced anymore. There can be temporary fix by maybe detecting this error and immediately refreshing the video automatically as that might temporarily resolve the problem until a fix is found.

**Comment by inotia00** [comment]
> 

This issue has been around for several months and no one has been able to find a valid fix.
(Including me and the ReVanced Team and MicroG developers)

It is speculated that over time, MicroG users will find it increasingly difficult to use.

**Comment by TheRedStormer** [comment]
Just switched from regular Vance's to revanced extended. I'm having the same issue but it's sometimes after 45 seconds or so. I live in Texas so I doubt it's really country specific. It's been happening since yesterday.

**Comment by sdoeringNew** [comment]
> @inotia00 [..] The playback is flawless when incognito mode is turned on or when you log out of the Google account. [..]
Since today I get the endless buffering even in incognito mode. Even with the typical 1:39min timestamp.

**Comment by shakir777** [comment]
This is happening with those who used YouTube vanced, I think YouTube has flagged us now we are unable to watch videos on revanced as the video keeps stopping so YouTube thinks eventually we will get irritated and switch to official ad mongering YouTube, but that ain't happening we will patiently wait till the issue is resolved or might as well root our devices if nothing else works. Good luck to hardworking devs.

**Comment by erikbass92** [comment]
> This is happening with those who used YouTube vanced, I think YouTube has flagged us now we are unable to watch videos on revanced as the video keeps stopping so YouTube thinks eventually we will get irritated and switch to official ad mongering YouTube, but that ain't happening we will patiently wait till the issue is resolved or might as well root our devices if nothing else works. Good luck to hardworking devs.

Even official YouTube starts buffering now, so that won't be an option either. Switching to an older microG is fine for some time if you don't want to make a new account or go incognito. Browser YouTube is unaffected, so that's an option as well.

**Comment by ronin08** [comment]
> > This is happening with those who used YouTube vanced, I think YouTube has flagged us now we are unable to watch videos on revanced as the video keeps stopping so YouTube thinks eventually we will get irritated and switch to official ad mongering YouTube, but that ain't happening we will patiently wait till the issue is resolved or might as well root our devices if nothing else works. Good luck to hardworking devs.
> 
> Even official YouTube starts buffering now, so that won't be an option either. Switching to an older microG is fine for some time if you don't want to make a new account or go incognito. Browser YouTube is unaffected, so that's an option as well.

even old microg doesn't solve the problem!

**Comment by erikbass92** [comment]
> 

Yup, it certainly does not work anymore! :( Neither does incognito or VPN. I've switched to NewPipe until this issue is fixed. I'm sick of using all of these workarounds, and most people don't want to switch to/make a new Google account. Really annoying.

**Comment by ronin08** [comment]
try libretube, better than newpipe imo

**Comment by trmdi** [comment]
> > 
> 
> Yup, it certainly does not work anymore! :( Neither does incognito or VPN. I've switched to NewPipe until this issue is fixed. I'm sick of using all of these workarounds, and most people don't want to switch to/make a new Google account. Really annoying.

Why not just logout your microg acc?

**Comment by Sappurit** [comment]
Android 6.0 and Vanced Extended 17.34.36 and Vanced microG 0.2.26.225014 = Work Well
Android 11.0 and Vanced Extended 18.08.38 and Vanced microG 0.2.24.220220 = Black Hole ( Will try to update to 18.08.39 and 0.2.27.230755. 

Welcome back  old school --rip-lib command.

**Comment by shakir777** [comment]
So what I do now is whenever the video stops playing I goto to the next video then come back to the video I was watching then it plays every time video stops that's what I do it's painful but I make sure I finish watching the whole video. 😭

**Comment by EnanInoa** [comment]
I don't know why, but this bug is not longer affecting me since last night

**Comment by Chessus** [comment]
> I don't know why, but this bug is not longer affecting me since last night

me either yesterday but started again today

**Comment by madhurvarshney** [comment]
> I don't know why, but this bug is not longer affecting me since last night

Same with me. I was using a new Google account for the last 4 days but today I saw there is a new version of microG available (v0.2.27.230755) so I updated it. And although it said the playback issue cannot be resolved on the microG side but still I switched back to my main Google account today to see if the issue still persists. Surprisingly, I did not face the issue since then.

**Comment by gitvitox** [comment]
Issue isn't happening for me anymore as well. I didn't Update anything. I am on a relatively old MicroG Version and it works even with the old YouTube Vanced.

My Versions which it currently works on:

MicroG: 0.2.22.212658
YouTube Vanced: 17.03.38
YouTube ReVanced: 18.03.36

I don't know what happened here. But as long as it works I'm happy.

**Comment by trmdi** [comment]
> Issue isn't happening for me anymore as well. I didn't Update anything. I am on a relatively old MicroG Version and it works even with the old YouTube Vanced.
> 
> My Versions which it currently works on:
> 
> MicroG: 0.2.22.212658 YouTube Vanced: 17.03.38 YouTube ReVanced: 18.03.36
> 
> I don't know what happened here. But as long as it works I'm happy.

So can you tell what you were testing in the previous comment?

**Comment by madhurvarshney** [comment]
> > I don't know why, but this bug is not longer affecting me since last night
> 
> Same with me. I was using a new Google account for the last 4 days but today I saw there is a new version of microG available (v0.2.27.230755) so I updated it. And although it said the playback issue cannot be resolved on the microG side but still I switched back to my main Google account today to see if the issue still persists. Surprisingly, I did not face the issue since then.

Well, it didn't last for long. It was working fine only for yesterday. The issue started happening today. Now I have switched back to my new Google Account.

**Comment by eaui1997** [comment]
Vanced MicroG v0.2.27.230755 fixed this problem. 👍

**Comment by Dewrow** [comment]
Well idk how. But it fixed itself.

**Comment by trmdi** [comment]
> Vanced MicroG v0.2.27.230755 fixed this problem. 👍

It does not fix anything. Probably Google just doesn't test your account. My acc still has the issue.

**Comment by mindforger** [comment]
i THINK i fixed it for now by changing the DNS on my phone to adguard ... But maybe it will return . Or maybe yt did dial it back a bit or just takes a step back for the next swing

**Comment by Shiroe93** [comment]
After almost a week of having this issue confirm wireguard works
I hope @inotia00 or the vanced team can use this info for a fix

**Comment by erikbass92** [comment]
Some of these people commenting here need to understand that "oh it works for me it must be fixed" or "it's fine for me, I never had an issue" isn't the case for everyone. It's not fixed or normal for everyone. Try to understand what's going on before commenting. So damn annoying.

**Comment by Shiroe93** [comment]
I don't know to whom you are talking specifically but I don't recall anyone saying it's fixed for everyone but If someone have done something specific that made the app start working again it's useful to know in my opinion because maybe the method used can be replicated

Even knowing that it started working again for no apparent reason can be useful because it means Google is experimenting right now to find the best way to implement this so it being not final means that it can change leaving (maybe) an opportunity to fix the problem

Obviously neither inotia00 or the revanced team are in any way obligated to do anything if they don't want to but knowing that a specific setup worked for someone is always worth knowing when there is a problem because it can lead to a solution

Personally i subscribed to this thread and tried everything that resembled a solution until 3 message ago when I found the one that worked (for me)

To be clear it's not that seeing some ads it's going to kill me but I find pretty egregious that Google it's locking background play (or screen off play) behind a 12$ paywall since those are feature of the os and not of the app specifically 
I'm m more than happy to pay YouTube premium if Google decides to add value to the subscription with things like less compression and better quality overall by I will be caught dead before I start to pay for something that was free at the beginning only to hook me into paying later (because like a lot of other silicon Valley company Google knew from day one that YouTube was not sustainable solely with the ad but they did so they could aquire user to do a simple bait and switch
In my opinion a commercial project should be able to stand on it's leg from day one if not then it needs to rethink is business model (I'm not saying that can't be an experimental phase frist)
So util YouTube premium becomes truly premium I'm grateful for anyone that post even the most stupid solution that might work

**Comment by Shiroe93** [comment]
The issue as returned for me even with adguard dns

**Comment by erikbass92** [comment]
> The issue as returned for me even with adguard dns

Same here. It was working fine. I'll try again with proton VPN on for the added benefit of wireguard. Everything I try just goes to shit and the buffering comes back after a day or two. Really frustrating.

**Comment by erikbass92** [comment]
For anyone looking for a somewhat decent workaround, get Firefox (stable/beta), grab some of the adblocking and anti-tracking add-ons, and finally paste this in as your private DNS in your phone settings: dns.adguard-dns.com 

Sponsors will be there, but no ads at least, and it's pretty smooth. Hopefully this gives anyone trying some relief. 🙂

**Comment by erikbass92** [comment]
Just a heads up if there's anyone that wasn't aware, the buffering is happening on the official YouTube app as well. Removing microG/Revanced does nothing, VPN with wireguard does nothing. I guess once you're marked by Google, you're not getting away from this issue. 

I just don't understand how I can use the same account in a browser, or maybe a smart tv and laptop but not face this issue. 🤔

**Comment by trmdi** [comment]
> I just don't understand how I can use the same account in a browser, or maybe a smart tv and laptop but not face this issue. thinking

google can do whatever they want.

**Comment by kroimon** [comment]
> Just a heads up if there's anyone that wasn't aware, the buffering is happening on the official YouTube app as well. Removing microG/Revanced does nothing, VPN with wireguard does nothing. I guess once you're marked by Google, you're not getting away from this issue.

For me, the official app started working again after uninstalling MicroG, but it might also just been coincidental because some kind of timeout occurred.

What seems clear so far: it doesn't happen to everybody, it doesn't happen all the time (A/B testing?) but it gets worse (even VPNs and incognito mode are affected now).

They also only seem to flag by device or app type, so even if the apps are affected, browser versions (even on the same phone, but also on smart TVs) still work.

**Comment by erikbass92** [comment]
> 

A/B testing seems to be what's going on, my wife used Vanced and Revanced and so far she hasn't had this issue. I wonder if it's also the device being used as you said? I'm getting a new phone in the next month or so and I'll definitely be checking this out.

**Comment by erikbass92** [comment]
Just gonna dump the VPN honestly, I'd have to keep it running on top of YouTube (which I use often) which means my phone gets it's battery wiped out and reaches magma temperatures. 😵

**Comment by L1s4R** [comment]
I tried everything as well, but I believe the problem is not on vanced or microg, it started since the last updates of Android auto OR Android system WebView in every phone that uses it, to interfere the vanced and revanced apps, 'perhaps'.
Watching videos directly in the webpage seems is not affected, I did it and was perfect, the problem only persists watching videos in apps like youtube, vimeo, dailymotion and even twitch, I have all with this same forever loading thing, very annoying :/
And I hope this is only temporary, since some video apps are not connected to youtube and it's affecting apps in general.

**Comment by Shiroe93** [comment]
> I tried everything as well, but I believe the problem is not on vanced or microg, it started since the last updates of Android auto OR Android system WebView in every phone that uses it, to interfere the vanced and revanced apps, 'perhaps'.
> Watching videos directly in the webpage seems is not affected, I did it and was perfect, the problem only persists watching videos in apps like youtube, vimeo, dailymotion and even twitch, I have all with this same forever loading thing, very annoying :/
> And I hope this is only temporary, since some video apps are not connected to youtube and it's affecting apps in general.

Very interesting I never thought of a generalized issue because in my case the official youtube app does not display the same problem but this could mean there's hope for some fix in the future

**Comment by L1s4R** [comment]
> >
> 
> Very interesting I never thought of a generalized issue because in my case the official youtube app does not display the same problem but this could mean there's hope for some fix in the future


I hope so...
And if I am not wrong, the problem can be different in some phone models too.

I am always suspicious of Android/Google *System Updates, and I noted this problem started since I updated  both last month.
Uninstalling updates won't work since it's already writen in internal system, and disabling it will turn off some useful tools and systems.

This is a mess... lol

**Comment by L1s4R** [comment]
Ah btw, I live in Japan, this is global issue

**Comment by erikbass92** [comment]
> > > 
> > 
> > 
> > Very interesting I never thought of a generalized issue because in my case the official youtube app does not display the same problem but this could mean there's hope for some fix in the future
> 
> I hope so... And if I am not wrong, the problem can be different in some phone models too.
> 
> I am always suspicious of Android/Google *System Updates, and I noted this problem started since I updated both last month. Uninstalling updates won't work since it's already writen in internal system, and disabling it will turn off some useful tools and systems.
> 
> This is a mess... lol

So this issue is more deeply rooted than specifically YouTube. Could it be any video streaming app where you've logged in with your Google account then? We could test this with several apps and update here, I think it might be helpful for the devs to figure something out.

**Comment by L1s4R** [comment]
> > 
> 
> So this issue is more deeply rooted than specifically YouTube. Could it be any video streaming app where you've logged in with your Google account then? We could test this with several apps and update here, I think it might be helpful for the devs to figure something out.

I don't think so, since my vimeo, dailymotion and twitch are all different accounts from youtube.

I also noticed the app 'Private computer services' which is useful for 'live caption' and 'now playing' features on videos is constantly asking for an update, for the second time in 2 weeks, and since they all are from Google LLC they must have something to so with it.

If devs can have a look in all, ask them to check all these apps :
Android system webview
Android auto
Private compute services

There is a new app which is being updated

**Comment by erikbass92** [comment]
> > > 
> > 
> > 
> > So this issue is more deeply rooted than specifically YouTube. Could it be any video streaming app where you've logged in with your Google account then? We could test this with several apps and update here, I think it might be helpful for the devs to figure something out.
> 
> I don't think so, since my vimeo, dailymotion and twitch are all different accounts from youtube.
> 
> I also noticed the app 'Private computer services' which is useful for 'live caption' and 'now playing' features on videos is constantly asking for an update, for the second time in 2 weeks, and since they all are from Google LLC they must have something to so with it.
> 
> If devs can have a look in all, ask them to check all these apps : Android system webview Android auto Private compute services
> 
> There is a new app which is a new release called 'Google partner setup' and had no idea it was here since February 23rd.
> 
> If something is being installed and written in the internal system causing all this problem, I am sure must be the recently system updates.
> 
> Devs will work hard to find out how to solve this problem :/

Huh, wow... This is just getting more ridiculous by the day. I think I'm just gonna stay from Revanced for a while until something is figured out, I can't imagine repeatedly logging in with microG would be a good thing. Maybe that will give Google less incentive to A/B test. 

I can survive with the browser version for now, at least I can use YouTube normally without ads. There are still sponsors, but that's fine I guess.

**Comment by L1s4R** [comment]
> 
> Huh, wow... This is just getting more ridiculous by the day. I think I'm just gonna stay from Revanced for a while until something is figured out, I can't imagine repeatedly logging in with microG would be a good thing. Maybe that will give Google less incentive to A/B test.
> 
> I can survive with the browser version for now, at least I can use YouTube normally without ads. There are still sponsors, but that's fine I guess.

The reason I opt for webdesigner, not programmer lol

In case of keeping trying vanced or revanced, just don't update all in once. I let the last one out of date and for 2 days it seems fine the YouTube in my mobile device.

But don't forget to always clean your app cache and once in a while even your data doing the log out.

Less you let information, less they collect it from you.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.164.30](https://github.com/inotia00/revanced-patches/releases/tag/v2.164.30)

**Comment by shakir777** [comment]
Is it fixed?

**Comment by Shiroe93** [comment]
My question is
 on top of wich version should this new version of patches have to be installed?

**Comment by shakir777** [comment]
Also need a guid like how to install the patch please.

**Comment by inotia00** [comment]
refer [documentation](https://github.com/inotia00/revanced-documentation/wiki/Method-3.-Using-official-ReVanced-Manager-(Android))

**Comment by shakir777** [comment]
Thank you for your help @inotia00 we love and respect your hardwork l.

**Comment by Shiroe93** [comment]
>  . . . 
> 
> What on earth? 
> 
> Go read literally any of the documentation or guides that are publicly available. This is an issue tracker, not a support forum.

You are absolutely right sorry everyone my bad thanks anyway to @inotia00 for the patch and for linking me the documentation

**Comment by Spacellary** [comment]
Inotia is a true GigaChad

**Comment by Shiroe93** [comment]
Unfortunately budgeting is sta to return for me

**Comment by Spacellary** [comment]
@Shiroe93 Just to make sure, you enabled Settings > ReVanced Extended > Miscellaneous > `Enable protobuf spoof`?

It was included in the settings patch and disabled by default, so that could be it.

**Comment by Shiroe93** [comment]
> @Shiroe93 Just to make sure, you enabled Settings > ReVanced Extended > Miscellaneous > `Enable protobuf spoof`?
> 
> It was included in the settings patch and disabled by default, so that could be it.

As I said in parentesys I've done that
