### ISSUE TITLE
bug(YouTube/Enable minimized playback): play button not available after playing Shorts

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#1539]
### Type

Other

### Tools used

ReVanced Manager

### Application

YouTube v18.36.39
ReVanced Patches v2.193.12

### Bug description

https://github.com/inotia00/ReVanced_Extended/assets/127908708/1aba046d-b757-4331-970c-b080c5d881d5

### Steps to reproduce

Shown in the video.

### Relevant log output

```shell
N/A
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.193.15](https://github.com/inotia00/revanced-patches/releases/tag/v2.193.15)

**Comment by Kuddus73** [comment]
> fixed in [revanced-patches-v2.193.15](https://github.com/inotia00/revanced-patches/releases/tag/v2.193.15)

Didn't fix it.

https://github.com/inotia00/ReVanced_Extended/assets/127908708/ba81b647-ab15-4ddc-9d67-07843411876a

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.193.18](https://github.com/inotia00/revanced-patches/releases/tag/v2.193.18)
