### ISSUE TITLE
bug(YouTube/Return YouTube Dislike): dislike count sometimes not shown in Shorts

### ISSUE THREAD

**Issue by jhon1282** [inotia00/ReVanced_Extended#1565]
### Type

Other

### Tools used

Revancify

### Application

YouTube v18.29.38~

### Bug description

When you look at the shorts, the counting of the DISLIKE is not shown.

### Steps to reproduce

1. Patch YouTube v18.29.38+
2. Play Shorts

### Relevant log output

```shell
Na
```

### Screenshots or videos

![Screenshot_2023-10-19-13-17-52-746_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/125223735/5a472a2e-7314-4f76-9040-1d14ec03535b)

### Solution

N/A

### Additional context

N/A

### Device Environment

Android 13
Miui 14 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
- [X] I have written the title and contents in English.
- [X] This issue does not reproduce on unpatched YouTube or YT Music.

**Comment by inotia00** [comment]
It does not reproduce on my side

It also doesn't reproduce on any device I have

It may be an issue with the API server, or there may be other causes

Please try patching with YouTube v18.33.40 which uses the old style Shorts actionbar and let me know the result

**Comment by jhon1282** [comment]
In 18.33.40 it works well
![Screenshot_2023-10-19-14-03-54-853_app rvpx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/125223735/e6d6b526-0fe3-4178-afc9-e2ad8ea99078)

**Comment by inotia00** [comment]
If so, it is a valid issue, even if it does not reproduce on my side

**Comment by girshcatt** [comment]
> If it helps, I tried the latest version of the original ReVanced, just out of curiosity, and I have the same issue 🤔. I assume it's a factor related to the new versions of YouTube. Many tanks for your availability 🙏

I can confirm it from my side and yes, it can be reproduced on ReVanced, you can create issue in ReVanced, i think that some of devs can have this issue and will reply you, just pin link on issue here and let inotia see when ReVanced will reply something

**Comment by inotia00** [comment]
In revanced-patches-v2.195.1, `v18.33.40` was added to `Spoof app version target`

For those experiencing this issue, please spoof with `v18.33.40`

**Comment by Kuddus73** [comment]
Shouldn't this be closed as the latest release's log says that it is fixed?

**Comment by inotia00** [comment]
Ah, I missed one thanks anyway

**Comment by jhon1282** [comment]
I apologize, but this issue is not fixed from my side.
I also changed devices but nothing changes.
![Screenshot_2024-05-26-16-20-41-353_app rvx android youtube](https://github.com/inotia00/ReVanced_Extended/assets/125223735/c737cb97-712e-4e3a-bfaf-be55871cb224)
[patch_log.txt](https://github.com/inotia00/ReVanced_Extended/files/15447889/patch_log.txt)

**Comment by jhon1282** [comment]
Ok, thank you very much.
RYD works fine for normal videos even if I don't log in with google account.
But not for shorts. This is really strange but that's how it is 😳
