### ISSUE TITLE
bug: RVX Manager doesn't display apps that aren't installed

### ISSUE THREAD

**Issue by KobeW50** [inotia00/ReVanced_Extended#2038]
### Type

Other

### Application

RVX Manager
v1.20.2

### Bug description

When a patchable app (ie: YouTube, YT Music, or Reddit) is not installed it does not appear in the app list in the RVX Manager. This makes it difficult for users to determine what the suggested version is for that app.

**Example**

Here is a screenshot from the **ReVanced** Manager, which correctly shows the app list when only YouTube is installed:

![Screenshot_20240516_121051_ReVanced Manager](https://github.com/inotia00/ReVanced_Extended/assets/84587632/684a138a-2ec7-44a4-8949-8618ba712135)

Here is a screenshot from **RVX** Manager:

![Screenshot_20240516_121102_RVX Manager](https://github.com/inotia00/ReVanced_Extended/assets/84587632/c5d05b99-896e-4eda-9a6f-83e58608c530)

### Device Environment

Android 14 
S22+
OneUI 6

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
This feature has not been provided since RVX Manager was first forked.
Here's why:

1. For some reason, RVX Manager uses the app list provided by the official ReVanced.
: Therefore, there was a bug where a list of apps not provided by RVX Patches was displayed.
e.g. RVX patch does not provide a patch for Spotify, but it recognizes that it supports Spotify, so Spotify is displayed in the not installed app list.

2. RVX patch supports only three apps: YouTube, YT Music, and Reddit.
: Therefore, there is no major inconvenience without displaying the list of apps that are not installed.

For this reason, the list of not installed apps is hidden by default by commit https://github.com/inotia00/revanced-manager/commit/a00750bc69c197905b694508e4804145ae2fc1c5.

This has been maintained since the RVX Manager was first forked, and if this 'bug' is not reproduced in the latest ReVanced Manager, it would be okay to roll back the commit.

**Comment by Vertuhai** [comment]
> When a patchable app (ie: YouTube, YT Music, or Reddit) is not installed it does not appear in the app list in the RVX Manager. This makes it difficult for users to determine what the suggested version is for that app.

I see no reason to worry about this; only three applications are being patched from inotia00, as he indicated.
After all, in order to patch you need to at least understand what you are doing, and if you don’t know that, then there is no point in patching, so something like this.

**Comment by inotia00** [comment]
I checked and found that this bug was a valid bug in rvx manager v1.3.8, when rvx manager was first forked, but it is no longer reproduced now.

About a year has passed since rvx manager was first forked, and it seems that this bug was fixed at some point.

I think it would be okay to roll back the commit https://github.com/inotia00/revanced-manager/commit/a00750bc69c197905b694508e4804145ae2fc1c5

**Comment by inotia00** [comment]
reflected in [rvx manager 1.20.3](https://github.com/inotia00/revanced-manager/releases/tag/v1.20.3)

**Comment by Francesco146** [comment]
I'm still facing this in the latest release. does this apply only for the default source?

**Comment by inotia00** [comment]
I'm not sure.
I haven't tested it on anything other than the default source and the RVX fork.

**Comment by jsjajajjajaashhbsbabhsshhshs** [comment]
![Uploading Screenshot_2024-05-21-08-15-26-654_app.rvx.manager.flutter.jpg…]()

It's always like this what should I do

**Comment by jsjajajjajaashhbsbabhsshhshs** [comment]
I can't update the app it's always stuck at " Downloading update . . . "

**Comment by KobeW50** [comment]
> I can't update the app it's always stuck at " Downloading update . . . "

You can download the newest apk from inotia00's ReVanced Manager repository

**Comment by KobeW50** [comment]
> I can't update the app it's always stuck at " Downloading update . . . "

You can download the newest apk from inotia00's ReVanced Manager repository
