### ISSUE TITLE
bug: Info Cards related

### ISSUE THREAD

**Issue by fedonr** [inotia00/ReVanced_Extended#212]
### Type

Cosmetic

### Application

YouTube v18.04.35

### Bug description

Basically when you have : Hide Info Cards patched, but you can disable it from Settings.

Here, the infocards do show up, but the issue is when you tap on Info Card, it always takes you to Description of the video. While the info panel where the info card should take you is completely missing.

### Steps to reproduce

Add Hide Info Cards patch

Now you can disable it from Settings.

Here, the infocards do show up, but the issue is when you tap on Info Card, it always takes you to Description of the video (missing info panel)

### Relevant log output

```shell
N/A
```

### Device Environment

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
Fortunately, it is a reproduction issue and will be fix in the next releases

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.159.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.159.1)

**Comment by Stovehead** [comment]
I still have this issue on YouTube v19.47.53 patched on December 29th.
