### ISSUE TITLE
bug(YouTube/Video Information): App crash when casting

### ISSUE THREAD

**Issue by AykhanUV** [inotia00/ReVanced_Extended#2309]
### Type

Error at runtime

### Tools used

CLI

### Application

Youtube 19.16.39, i also tried 19.25.39, 19.26.42

### Bug description

When i try to cast video the app crashes

### Additional context

Everything worked perfect till [v4.10.4-dev.1](https://github.com/inotia00/revanced-patches/releases/tag/v4.10.4-dev.1) but i saw this bug releases after that
I have used cli version 4.6.1 for this

### Device Environment

1- Poco X6 Pro Android 14, HyperOS
2- Samsung S22 Ultra Android 14, OneUI 6.1

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
Please turn off the `Spoof client` and report back the results.

**Comment by AykhanUV** [comment]
Tried it now does not matter on/off, also it crashes the moment it connects to tv

**Comment by inotia00** [comment]
If so, I have no idea

Please exclude patches one by one and report back which patch is causing the bug

**Comment by AykhanUV** [comment]
I edited some default settings in integrations hide toolbar cast button, hide plyaer cast button. Can it be due to that?

**Comment by AykhanUV** [comment]
Hey i tried using all default settings both on cli and rvx manager, i used youtube 19.16.39, 19.25.39, 19.26.42 and i think this bug is about patches

**Comment by YT-Advanced** [comment]
Maybe recent reflaction from Revanced Team ?

**Comment by AykhanUV** [comment]
I checked revanced too, it worked on both my devices

**Comment by inotia00** [comment]
> Can you try this yourself? Because casting worked perfectly before last patch

I can't test it on my side since I don't use casting

As I mentioned earlier, please exclude the patches one by one and report back which one causes the issue

**Comment by AykhanUV** [comment]
I just did what you said, excluded patches one by one untill gmsCore support was only one left and still bug is there.

**Comment by NMBlanco** [comment]
Same issue for me here. It crashes no matter what I try. Going back to the stable patch version (4.12.1) also doesn't fix the issue.

**Comment by inotia00** [comment]
> gmsCore support was only one left and still bug is there.

Thank you for response

**Comment by inotia00** [comment]
fixed in [revanced-patches-4.12.3](https://github.com/inotia00/revanced-patches/releases/tag/v4.12.3)

**Comment by 0xmarshall00** [comment]
How to enable translucent navigation bar ??, after the new update and patches the experimental choice was disappeared

**Comment by GucekPL** [comment]
@inotia00 using 19.28.35 matters? I'm asking because app is still crashing when i try cast a video

**Comment by inotia00** [comment]
The issue was reported on YouTube 19.16.39, and the crash on YouTube 19.16.39 was fixed, so the issue was closed

YouTube 19.28.35 is not a supported version, so it was not tested
