### ISSUE TITLE
bug: Patching issues RVX Manager: 1.21.1

### ISSUE THREAD

**Issue by 54m4d** [inotia00/ReVanced_Extended#2363]
### Type

Error while patching

### Tools used

RVX Manager

### Application

v19.16.39

### Bug description

I tried reinstalling RVX Manager multiple times, force stopping and clearing cache, but none of these actions made an improvement.

### Error logs

```shell
- Device Info
RVX Manager: 1.21.1
Android version: 14
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v19.16.39 (Suggested: 19.16.39)
Patches version: v2.228.0-dev.15
Patches added: Hide Shorts dimming
Patches removed: Force snackbar theme, Spoof app version, Custom Shorts action buttons, Force player buttons background, Theme, Enable debug logging, Translations, Return YouTube Dislike
Default patch options changed: Visual preferences icons [RVX settings menu icon: gear]

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Remove unused library: true
Use pre-release: true
Patches source: anddea/revanced-patches
Integration source: anddea/revanced-integrations

- Logs
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing temporary files directory
Decoding resources
Executing patches
Applied 48 patches
Compiling patched dex files
Compiled 8 dex files
An error occurred:
java.io.FileNotFoundException: /data/user/0/app.rvx.manager.flutter/cache/patcher/tmp-WUFJFY/revanced-temporary-files/patched/dex/classes7.dex: open failed: ENOENT (No such file or directory)
 at libcore.io.IoBridge.open(IoBridge.java:574)
 at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289)
 at com.android.tools.smali.dexlib2.writer.io.FileDataStore.<init>(Unknown Source:7)
 at lanchon.multidexlib2.DexIO.writeMultiDexDirectoryCommon(Unknown Source:80)
 at lanchon.multidexlib2.DexIO.access$000(Unknown Source:0)
 at lanchon.multidexlib2.DexIO$1.call(SourceFile:0)
 at lanchon.multidexlib2.DexIO$1.call(SourceFile:0)
 at java.util.concurrent.FutureTask.run(FutureTask.java:264)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
 at java.lang.Thread.run(Thread.java:1012)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
 at libcore.io.Linux.open(Native Method)
 at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
 at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
 at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
 at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8782)
 at libcore.io.IoBridge.open(IoBridge.java:560)
 ... 10 more
```

### Device Environment

Android version: 14

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by DarkSanctuary** [comment]
Already reported: #2355 

In the meantime use revancify, tutorial:

https://www.reddit.com/r/revancedextended/comments/16019aj/how_to_install_with_revancify_tutorial/?rdt=48118

**Comment by KobeW50** [comment]
This error is different than #2355 

Also, that revancify tutorial is a bit outdated. The [documentation](https://github.com/inotia00/revanced-documentation/blob/main/docs/revancify.md) or [this guide](https://www.reddit.com/r/revancedextended/comments/1edzyhb/guide_for_getting_started_with_revancify/) is better

**Comment by 54m4d** [comment]
I know how to use other patching methods, but how do you know it's the same issue?

**Comment by kitadai31** [comment]
Can you provide storage size and how mach storage left?

**Comment by 54m4d** [comment]
> Can you provide storage size and how much storage left?

This is actually a good point, because last time I successfully patched the app, I had more storage space.

Currently, I have 2GB of storage left.

**Comment by DarkSanctuary** [comment]
> > Can you provide storage size and how much storage left?
> 
> This is actually a good point, because last time I successfully patched the app, I had more storage space.
> 
> Currently, I have 2GB of storage left.

I have 224gb of storage free and 7gb of ram free and I couldnt install the patched app with RVX Manager.

**Comment by kitadai31** [comment]
> > Can you provide storage size and how much storage left?
> 
> This is actually a good point, because last time I successfully patched the app, I had more storage space.
> 
> Currently, I have 2GB of storage left.

Thank you
Then it is this issue: https://github.com/ReVanced/revanced-manager/issues/2120

When storage space is not enough, Android system deletes Manager's temporary directory even while patching.
Fixed in Compose Manager (developing next major version of ReVanced Manager)

**Comment by 54m4d** [comment]
> > > Can you provide storage size and how much storage left?
> > 
> > 
> > This is actually a good point, because last time I successfully patched the app, I had more storage space.
> > Currently, I have 2GB of storage left.
> 
> Thank you Then it is this issue: [ReVanced/revanced-manager#2120](https://github.com/ReVanced/revanced-manager/issues/2120)
> 
> When storage space is not enough, Android system deletes Manager's temporary directory even while patching. Fixed in Compose Manager (developing next major version of ReVanced Manager)

Thanks! That's very good to know. I will try to free up some space and then try again.

**Comment by ILoveOpenSourceApplications** [comment]
Hey @inotia00, will you be bumping RVX Manager to v1.21.2 with the next patch release?

**Comment by inotia00** [comment]
fixed in [rvx-manager-1.21.3](https://github.com/inotia00/revanced-manager/releases/tag/v1.21.3)

**Comment by kitadai31** [comment]
It is not fixed yet!
https://github.com/ReVanced/revanced-manager/pull/2135 solves EACCESS (Permission denied) error for `in.apk` when patching SoundCloud, that is separate from this issue (ENOENT while patching)

https://github.com/ReVanced/revanced-manager/pull/2193 directly fixes this issue

**Comment by inotia00** [comment]
Well.. I haven't received any issues related to RVX Manager since a few weeks ago

The reasons for this decision are as follows:

1, RVX Manager is a minimally modified fork of ReVanced Manager
: RVX Manager is a fork to maintain compatibility with my patches

Most issues that occur in RVX Manager can be reproduced in ReVanced Manager

It's better to simply open an issue in the ReVanced Manager repository for maintenance and support

2, Even if a user opens an issue here, there is nothing I can do
: If a user opens an issue, they have to re-open the same issue in the ReVanced Manager repository to get support for the bug

3, RVX Manager is an option that exists simply to ensure compatibility with my patches
: There are other patching methods available in the docs besides RVX Manager

For this reason, all issues related to RVX Manager that were opened in the last few weeks have been marked as Not planned and closed
