### ISSUE TITLE
bug: Hide upcoming Videos only hides Title (Livestream)

### ISSUE THREAD

**Issue by 30b0** [inotia00/ReVanced_Extended#2427]
### Type

Cosmetic

### Tools used

RVX Manager

### Application

YouTube v19.16.39 | Patches v4.15.1-dev.1

### Bug description

The Feature "Hide UPCOMING Videos" only hides the Title and not the clickable Video in the Subscription Feed. In this Case it's a upcoming Livestream, if that makes a difference, I don't know about upcoming Videos.

![Screenshot_20241008-184313_YouTube](https://github.com/user-attachments/assets/7114258c-e736-437c-beab-9631f88ec5ed)
![Screenshot_20241008-184458_YouTube](https://github.com/user-attachments/assets/66263de2-4857-47d6-ab51-f44efcc18d71)

### Device Environment

Android 14, CrDroid 10.8, OnePlus 9 Pro, Root with Magisk

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I didn't use any settings marked as `Experimental Flags`.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by UnknownErrorNotFound** [comment]
In my case upcoming videos are not hid at all:

![Screenshot_20241011_012302_RVX YouTube](https://github.com/user-attachments/assets/4e8c9887-9e8d-467c-ae06-4b355b6b1464)

![Screenshot_20241011_012347_RVX YouTube](https://github.com/user-attachments/assets/0e2d34d2-cb7e-483b-b128-d17d15d45d87)

YouTube v19.16.39
Patches v4.15.1-dev.1

**Comment by inotia00** [comment]
fixed in [revanced-patches-4.14.2](https://github.com/inotia00/revanced-patches/releases/tag/v4.14.2)

```
fix(YouTube/Hide feed components): `Hide UPCOMING video` setting now only hides the video when the thumbnail can be hidden
```

**Comment by UnknownErrorNotFound** [comment]
> fixed in [revanced-patches-4.14.2](https://github.com/inotia00/revanced-patches/releases/tag/v4.14.2)
> 
> ```
> fix(YouTube/Hide feed components): `Hide UPCOMING video` setting now only hides the video when the thumbnail can be hidden
> ```

So we have to downgrade to older patches? Thats kinda stupid solution isnt it? In my case Im using the latest dev and the patch is completely broken.

**Comment by UnknownErrorNotFound** [comment]
@inotia00 

Im still having issues with this patch where upcoming videos are not getting hidden, check tauri reacts channel.

**Comment by inotia00** [comment]
Videos will only be hidden from feeds if the thumbnail can be hidden

(e.g. subscription feed, search results)

Otherwise, they will not be hidden if there is a possibility of bugs

**Comment by UnknownErrorNotFound** [comment]
> Videos will only be hidden from feeds if the thumbnail can be hidden
> 
> (e.g. subscription feed, search results)
> 
> Otherwise, they will not be hidden if there is a possibility of bugs

Well its not hiding them from search results on my end.

**Comment by inotia00** [comment]
> Well its not hiding them from search results on my end.

I would have liked to leave it as an experimental flag if possible, but it is too buggy
It will be removed in the next release

**Comment by Rafa-Segovia** [comment]
Does this still work to hide upcoming videos from subscriptions feed?

![Image](https://github.com/user-attachments/assets/e210f821-8c9a-4e9c-8c8c-0c3c40da4d72)

Which versions do I need?
