### ISSUE TITLE
bug: RVX crashing when clicking and opening up Youtube links from Reddit

### ISSUE THREAD

**Issue by afk789** [inotia00/ReVanced_Extended#2607]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

RVX 19.44.39
Patches: v5.1.3 / v5.1.2 / v5.1.1

### Bug description

Ever since patches 5.1.1 were released clicking on Youtube links in Reddit causes RVX to crash. This issue wasn't present before. I have reinstalled unpached Youtube and this issue is not present. Step 1 Find a Youtube link in Reddit Step 2. Click on it and it opens in a broswer. Step 3. Select RVX as the app to open it and then it crashes.

### Device Environment

Android 8.1 Oreo Samsung Experience 9.5

### Acknowledgements

- [X] This issue does not reproduce on unpatched YouTube or YT Music.
- [X] This issue is not a duplicate of an existing bug report.
- [X] I did not use any settings marked as `Experimental Flags`.
- [X] I did not use `pre-release` (dev branch).
- [X] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] I have written the title and contents in English.

**Comment by inotia00** [comment]
It doesn't reproduce on my side

Please attach crash log

**Comment by afk789** [comment]
I must add that if you click on any Youtube link in a mobile browser and Discord RVX crashes also so it's Youtube links in general that make RVX crash starting with the 5.1.1 patches.

**Comment by afk789** [comment]
[log.txt](https://github.com/user-attachments/files/18225448/log.txt)
There's my log file.

**Comment by marieSt3wartizzle** [comment]
I have this same issue too. That is what happens if I try to open YouTube links directly from the browser 😲

**Comment by WsNyc00** [comment]
19.44.39 app (v5.1.3 patch) Crashes while opening youtube links from browsers (Using brave)
Patched 19.16.39 app doesn't crash (v5.1.3 patch)

**Comment by inotia00** [comment]
Exclude `Navigation bar components` patch and patch again

Please report back if the issue is reproduced

**Comment by afk789** [comment]
It still crashes when opening YouTube web links despite excluding Navigation bar components when patching.

**Comment by inotia00** [comment]
Fixed in revanced-patches-5.2.1-dev.3

(Tested on Android 15 AVD)

**Comment by inotia00** [comment]
Fixed in [revanced-patches-5.2.1](https://github.com/inotia00/revanced-patches/releases/tag/v5.2.1)

**Comment by afk789** [comment]
It's still crashing even with the latest patches.

**Comment by inotia00** [comment]
> [log.txt](https://github.com/user-attachments/files/18225448/log.txt) There's my log file.

Fix for this crash log has been reflected in revanced-patches-5.2.1.

> It's still crashing even with the latest patches so I believe this should remain open not closed.

If so, please attach a new crash log.

**Comment by afk789** [comment]
[log.txt](https://github.com/user-attachments/files/18329776/log.txt)
There's my logcat.

**Comment by inotia00** [comment]
This may have been fixed in [revanced-patches-5.2.2](https://github.com/inotia00/revanced-patches/releases/tag/v5.2.2)

**Comment by afk789** [comment]
It still crashes in 5.2.2. Opening Youtube web links from mobile web browser.

**Comment by inotia00** [comment]
This is really weird

It doesn't seem to be an issue on the RVX side anymore

Can you check if the issue is reproduced on unpatched YouTube 19.44.39?

**Comment by afk789** [comment]
No crashing on unpatched 19.44.39.

**Comment by inotia00** [comment]
Is the issue reproducible even when the `Custom braning icon for YouTube` patch is excluded?

**Comment by afk789** [comment]
Issue is still there even when excluding that patch.

**Comment by inotia00** [comment]
This may have been fixed in [revanced-patches-5.3.1](https://github.com/inotia00/revanced-patches/releases/tag/v5.3.1)

**Comment by afk789** [comment]
It'
