### ISSUE TITLE
Bug: Dislike count gets still removed after pressing like

### ISSUE THREAD

**Issue by NMBlanco** [inotia00/ReVanced_Extended#281]
### Type

Error at runtime

### Application

18.06.35

### Bug description

When pressing the like button on a video, the dislike count goes away and won't return after until I close the video and reopen it. 

### Steps to reproduce

Enable return dislike button patch, go to any video, press like button.

### Relevant log output

```shell
/
```

### Screenshots or videos

https://user-images.githubusercontent.com/12681440/219948884-96554436-f6ec-4167-a2c6-cfec0b6bc0f2.mp4

### Device Environment

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.164.18](https://github.com/inotia00/revanced-patches/releases/tag/v2.164.18)

**Comment by Vipin2003** [comment]
This is not fixed completely as if we remove like from video after liking, the dislike won't show.

**Comment by Vipin2003** [comment]
I know this...but check this.

https://streamable.com/y9rzib

It will be normal after scrolling a little bit.

**Comment by inotia00** [comment]
That video is a separate issue from this issue page
(check the title of this issue page)

Unfortunately, the issue in that video is impossible to fix.

It's a very minor issue, and if you scroll a little, you can see the dislike count again.

**Comment by Vipin2003** [comment]
It's okay...I was just informing for that bug.

Well, thanks for solving this.
