### ISSUE TITLE
bug: background color of splash animation is white

### ISSUE THREAD

**Issue by goensnap** [inotia00/ReVanced_Extended#2892]
### Type

Error at runtime

### Tools used

RVX Manager

### Application

Youtube v19.47.53

### Bug description

Case : applied themes is black/dark, but when opening Youtub app the background color of splash animation is white, not black.

Patch Version : 5.6.1 stable

List of used patch : 

Ads :
Hide ads

Alternative thumbnails :
Alternative thumbnails
Bypass image region restrictions

Feed :
Hide feed components
Hide feed flyout menu

General :
change form factor
Change live ring click action
Change start page
Disable forced auto audio tracks
Disable forced auto captions
Disable layout updates
Disable splash animation
Enable gradient loading screen
Hide layout components
Hook download actions
Navigation bar components
Remove viewer discretion dialog
Snack bar components
Spoof app version
Toolbar components

Player :
Ambient mode control
Change player flyout menu toggles
Description components
Disable haptic feedback
Disable resuming Miniplayer on startup
Fullscreen components
Hide action buttons
Hide comments components
Wide player buttons
Hide player flyout menu
Minplayer
Overlay buttons
Player components
Seekbar components

Shorts :
Disable resuming Shorts on startup
Shorts components

Swipe controls :
Swipe controls

Video :
Video playback

Miscellaneous :
Bypass UPL redirects
change share sheet
Disable QUIC protocol
Enable debug logsing
Enable OPUS codec
Open links externally
Remove background playback restrictions
Sanitize sharing links
Spoof streaming data
Watch history

Others :
Custom double tap length
Justom Shorts action buttons
GmsCore support
Hide accessibility controls dialog
Hide Shorts dimming
Hide shortcuts
Icon : Revancify Fed
Label
Return YouTube Dislike
Return YouTube Username
Sponsor Block
Theme : Materialyou + Amoled Black
Translations
Visual preferences icons

https://github.com/user-attachments/assets/33d609de-54b7-4b1a-b9d3-00dea7190637

![Image](https://github.com/user-attachments/assets/02086301-c7a8-4c9b-a310-74467abeb9e2)

### Error logs

```shell

```

### Device Environment

Samsung A52S 5G
Android 14
One UI 6.1
Non-Root Device

### Acknowledgements

- [x] This issue does not reproduce on unpatched YouTube or YT Music.
- [x] This issue is not a duplicate of an existing bug report.
- [x] I did not use any settings marked as `Experimental Flags`.
- [x] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.
- [x] I have written the title and contents in English.

**Comment by andylee516** [comment]
same problem for me too

**Comment by inotia00** [comment]
When tested on Android emulator, the issue is not reproduced.

Is it only reproduced on certain manufacturer ROMs?

**Comment by Aryan-Chauhan** [comment]
Yes, I'm also facing this issue.

Using latest stable patches and recommended APK version.

Dark theme is enabled in the app, but still getting white background in splash screen.

Everything was fine till v5.6.1-dev.4, I think it started with dev.5

Device: Realme 7 Pro
OS: Realme UI 3.0 (Android 12)

![Screenshot_2025-03-30-18-23-32-73_f22faf49515899f9781ec174a4d85388.jpg](https://github.com/user-attachments/assets/ce9e6e10-ebd1-4b35-9753-2196c71dd27f)

**Comment by GucekPL** [comment]
I have gray background, restore old splash is causing this - without this patch option, theme is working properly on app start.

![Image](https://github.com/user-attachments/assets/b53f0842-f1f1-40b5-a073-d4ba9a42871c)

**Comment by goensnap** [comment]
> I have gray background, restore old splash is causing this - without this patch option, theme is working properly on app start.
> 
> ![Image](https://github.com/user-attachments/assets/b53f0842-f1f1-40b5-a073-d4ba9a42871c)

I can confirm. I patch the original youtube apk again (v.19.57.43), this time without "restore the old style splash animation" patch option, and the background color is black, working perfectly normal like it used to be, just without the animated icon.

**Comment by inotia00** [comment]
It should have been fixed in revanced-patches-5.6.2-dev.1, but since the issue doesn't reproduce on my side, testing is needed.

**Comment by 30b0** [comment]
Still having the Issue with Patches v5.6.2-dev.1.

Performed a clean Mount install of the Application.
![Image](https://github.com/user-attachments/assets/dd07ba86-2aa6-453b-a079-b65cc0c0625e)

**Comment by farnurikhsan** [comment]
I am also still experiencing the same issue, even though I have used it Patches v5.6.2-dev.1.

**Comment by Aryan-Chauhan** [comment]
I updated to latest dev patches, but still facing the same issue.

**Comment by J4k-The-Reaper** [comment]
Still seeing same issue no matter what I do. Hope there's a fix soon

**Comment by inotia00** [comment]
In revanced-patches-5.6.2-dev.2, all commits related to the `Custom branding icon` patch were rolled back.

It should work.

**Comment by Aryan-Chauhan** [comment]
Now the issue is solved for me.

**Comment by farnurikhsan** [comment]
Yeah its work now

**Comment by J4k-The-Reaper** [comment]
I must be doing something wrong...cuz it's still white for me on dark theme. Patched using 19.47.53

**Comment by esperanzality** [comment]
Mine hasn't been fixed either.

**Comment by esperanzality** [comment]
If I set only YouTube to dark mode, it stays white. But when I set my phone to dark mode, YouTube turns black. Is this normal?

**Comment by inotia00** [comment]
Reflected in [revanced-patches-5.6.2](https://github.com/inotia00/revanced-patches/releases/tag/v5.6.2)
