### ISSUE TITLE
bug(YouTube - Hide feed components): Ticket shelves are not hidden in related videos

### ISSUE THREAD

**Issue by Kuddus73** [inotia00/ReVanced_Extended#2960]
### Type

Other

### Tools used

RVX Manager

### Application

YouTube v19.44.39
Patches v5.6.2

### Bug description

https://github.com/user-attachments/assets/52b0f2bd-a83f-40b7-98c0-c65ab011cde6

### Error logs

```shell

```

### Acknowledgements

- [x] This issue does not reproduce on unpatched YouTube or YT Music.
- [x] This issue is not a duplicate of an existing bug report.
- [x] I did not use any settings marked as `Experimental Flags`.
- [x] I have patched the APK according to the [documentation](https://github.com/inotia00/revanced-documentation#readme).
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.
- [x] I have written the title and contents in English.

**Comment by inotia00** [comment]
Fixed in [revanced-patches-5.7.1](https://github.com/inotia00/revanced-patches/releases/tag/v5.7.1)

**Comment by Kuddus73** [comment]
@inotia00 the bug is still present with patches v5.7.1:

https://github.com/user-attachments/assets/fe63ad58-5282-4049-94df-cbce3ca32435

**Comment by Kuddus73** [comment]
@inotia00 with patches v5.8.1-dev.1 it is still half visible:
![Image](https://github.com/user-attachments/assets/a935f056-2c20-4d5a-97c4-9fe1b5343a90)

**Comment by inotia00** [comment]
1. Turn on: Miscellaneous - Debugging - Enable debug logging & Log protocal buffer.

2. Go to where you see the ticket shelf.

3. Export to a file with Miscellaneous - Debugging - Export debug logs.

4. Upload the exported file.

**Comment by inotia00** [comment]
nvm, the issue is reproduced on my side
