### ISSUE TITLE
bug: Video quality presets not working

### ISSUE THREAD

**Issue by hi-im-karma** [inotia00/ReVanced_Extended#321]
### Type

Error at runtime

### Application

Version 18.06.41 non-root 

### Bug description

I often times encounter videos which wouldn't play with the highest available quality. For example wouldn't play with 4K even though I have set it as video presets.
This has been happening very frequently and I'm starting to think these settings aren't working anymore. It's pretty annoying as I have to manually set it to highest quality every time it happens, and I cannot trust RVX to play with highest available quality. Example; As you can see with the video below it does not play with 2160p instead it plays 1080p...

![Screenshot_20230223-212047948 (1)](https://user-images.githubusercontent.com/73917917/221023201-2c594c40-6edb-43b2-be67-f59395c7fdc5.png)

![Screenshot_20230223-212032895 (1)](https://user-images.githubusercontent.com/73917917/221023210-8f5bb24a-3d5f-46cf-8b74-2d0f0973e0ce.png)

**Comment by venkat2305** [comment]
Can you check with 1080p and 1440p

**Comment by inotia00** [comment]
Probably, it seems to be the same issue as this one https://github.com/inotia00/ReVanced_Extended/issues/106
This issue applies to some 4K videos as well as HDR videos.

**Comment by ILoveOpenSourceApplications** [comment]
Or it could be something due to the device hardware as well where YouTube forces down the quality of some videos.

**Comment by anyujinie** [comment]
> Or it could be something due to the device hardware as well where YouTube forces down the quality of some videos.

Not related to device. I have YouTube Vanced installed aswell and it **always** plays with highest preset quality.

**Comment by kazimmt** [comment]
> Not related to device. I have YouTube Vanced installed aswell and it **always** plays with highest preset quality.

I tried to reproduce the issue.
But it's working completely fine here.

**Comment by inotia00** [comment]
Does the issue still persist in the latest release?

**Comment by anyujinie** [comment]
> Does the issue still persist in the latest release?

I have to test and will report back

**Comment by GUImodder** [comment]
Hey, 
any updates on a possible solution?

**Comment by inotia00** [comment]
Issue is not reproducible

**Comment by GUImodder** [comment]
Is there some kind of log that would help you figure it out?

**Comment by anyujinie** [comment]
> Does the issue still persist in the latest release?

Issue still persists. A 2160p video started with 720p and I had to manually select 2160p...

**Comment by anyujinie** [comment]
Issue still persists. 4K videos very often playing at 1080p. The video quality presets are completely broken, rarely working...

**Comment by odkrys** [comment]
I noticed a problem while watching HDR videos. Revanced settings are set to 1440p.

After playing an HDR video > Play a low quality video (720p or 1080p) > And then play an HDR video again, it follows the quality of the previous video.

It feels like YouTube's quality settings overwrite revanced's quality settings.

https://www.youtube.com/watch?v=uhgnez5_2Qg

**Comment by inotia00** [comment]
> youtube 18.14.41 / patch v2.168.38
> 
> I noticed a problem while watching HDR videos. Revanced settings are set to 1440p.
> 
> After playing an HDR video > Play a low quality video (720p or 1080p) > And then play an HDR video again, it follows the quality of the previous video.
> 
> It feels like YouTube's quality settings overwrite revanced's quality settings.
> 
> https://www.youtube.com/watch?v=uhgnez5_2Qg

It's off topic https://github.com/inotia00/ReVanced_Extended/issues/106

**Comment by odkrys** [comment]
I also saw issue #106.
In the video I uploaded, it seems that two issues appear together.
The quality changes after 10 seconds and does not change to the quality(1440p) set in revanced.

**Comment by Mohammedibrahim15** [comment]
Is there any progress
When this issue first appear to me I openes an issue in repository
And when @inotia00 rolled back the commit regrading video quality the issue was fixed 
So i suggest if he could roll back the commit and we can test if the issue will be fixed or not 
It is not related to stock YouTube as it works fine in official Revanced 
https://github.com/inotia00/ReVanced_Extended/issues/1006#issuecomment-1546711922

**Comment by inotia00** [comment]
It is still not reproduced so it is impossible to fix on my side

maybe it's an issue with YouTube
(Google is currently testing offering 1080p resolution only to Premium users)

https://www.reddit.com/r/youtube/comments/14yqlo5/why_did_the_quality_of_the_videos_im_watching_are/

https://www.reddit.com/r/youtube/comments/14z6uzx/why_does_youtube_videos_keep_randomly_switching/

https://www.reddit.com/r/youtube/comments/14zaud0/1080p_premium_quality/

https://www.reddit.com/r/youtube/comments/14yxtm3/here_we_go/

**Comment by sssh7710** [comment]
> It is still not reproduced so it is impossible to fix on my side
> 
> maybe it's an issue with YouTube (Google is currently testing offering 1080p resolution only to Premium users)
> 
> https://www.reddit.com/r/youtube/comments/14yqlo5/why_did_the_quality_of_the_videos_im_watching_are/
> 
> https://www.reddit.com/r/youtube/comments/14z6uzx/why_does_youtube_videos_keep_randomly_switching/
> 
> https://www.reddit.com/r/youtube/comments/14zaud0/1080p_premium_quality/
> 
> https://www.reddit.com/r/youtube/comments/14yxtm3/here_we_go/

Genuine advanced works fine

**Comment by sssh7710** [comment]
> This is the realm of A/B testing
> 
> Depending on the version of the YouTube client, or depending on the Google account, it may or may not be designated as a test target.
> 
> They are even randomly targeted for this test regardless of platform, such as unpatched Android YouTube, YouTube Web, or YouTube TV.
> 
> If this issue doesn't reproduce in the official ReVanced, you're in luck
> just use it
> 
> What is controlled by the server side cannot be controlled by the client side.

Will paying the premium solve the problem?

**Comment by anyujinie** [comment]
> Will paying the premium solve the problem?

Im the author of this post and Im a premium member for many years. So no it does not solve anything and isn't related to the issue..

**Comment by sssh7710** [comment]
> > Will paying the premium solve the problem?
> 
> Im the author of this post and Im a premium member for many years. So no it does not solve anything and isn't related to the issue..

I think I need to pay the premium because the premium sub-account works well

**Comment by sssh7710** [comment]
Even if I pay for the premium, this app won't solve the problem

**Comment by sssh7710** [comment]
> This is the realm of A/B testing
> 
> Depending on the version of the YouTube client, or depending on the Google account, it may or may not be designated as a test target.
> 
> They are even randomly targeted for this test regardless of platform, such as unpatched Android YouTube, YouTube Web, or YouTube TV.
> 
> If this issue doesn't reproduce in the official ReVanced, you're in luck
> just use it
> 
> What is controlled by the server side cannot be controlled by the client side.

Will it be possible to solve the problem later?

**Comment by inotia00** [comment]
I can't fix it because it doesn't reproduce on my side

**Comment by sssh7710** [comment]
How about rolling back the recent update regarding this setting?

**Comment by inotia00** [comment]
This issue was opened on February 24th

Rolling back the code to May doesn't fix the issue

**Comment by inotia00** [comment]
Since it is an issue that does not reproduce at least on my side, it is impossible to fix on my side
(it works perfectly for me)

If someone can reproduce this issue, determine the cause, and merge the commits for the fix, they can open a Pull Request

All source code and history are public, so anyone can contribute

**Comment by sssh7710** [comment]
I just format the app and fix the resolution, so it works fine

**Comment by sssh7710** [comment]
Wouldn't it be a problem related to layout setting?

**Comment by sssh7710** [comment]
I found the cause
SpongeBlock is the problem
If I turn it off, it works well
Please inform the Sponblock developer of this issue

**Comment by sssh7710** [comment]
There was a problem again, so I think it's not a sponge block problem, but it's getting tangled when I load the settings

**Comment by sssh7710** [comment]
We're gonna test it a little bit more

**Comment by Mohammed1520** [comment]
> This issue was opened on February 24th
> 
> Rolling back the code to May doesn't fix the issue

https://github.com/inotia00/ReVanced_Extended/issues/1006#issuecomment-1546711922 
I had opened an issue on 13th May. And when inotia rolled back the commit everything worked fine. I know that this issue is opened since February. But why not trying to roll back commits to that of May and try

**Comment by sssh7710** [comment]
> > 이 문제는 2월 24일에 열렸습니다.
> > 코드를 5월로 롤백해도 문제가 풀렸는지
> 
> [#1006 (댓글)](https://github.com/inotia00/ReVanced_Extended/issues/1006#issuecomment-1546711922) 5월 13일에 폭로된 이슈가 드러났습니다. 그리고 inotia가 라켓을 저격했을 때 모든 것이 잘 작동했습니다. 이번 호는 2월부터 연재하는 것으로 알고 있습니다. 하지만 라켓을 5월로 롤백하고 시도하는 것은?

I think it's better to try rollback OrQ

**Comment by inotia00** [comment]
Too many refactorings in 3 months, that's impossible

I emphasize once again
Since this issue is not reproducible on my side, I cannot fix it

If the issue is not reproduced in the official ReVanced, just use it
