### ISSUE TITLE
The position of the subtitles is moved at the top

### ISSUE THREAD

**Issue by jhon1282** [inotia00/ReVanced_Extended#477]
### Type

Cosmetic

### Application

Youtube recommend version 18.09.39

### Bug description

If you activate the subtitles are displayed the high position instead of at the bottom as in the official version

### Steps to reproduce

Start video
Select subtitles 

### Relevant log output

```shell
https://streamable.com/5x3xbw
```

### Screenshots or videos

[https://streamable.com/5x3xbw
![Screenshot_2023-03-14-11-44-08-599_app rvx android youtubf](https://user-images.githubusercontent.com/125223735/224980085-80aec28a-be08-4602-9727-669b15d32779.jpg)
](url)

### Device Environment

Android 11, miui 12.5

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by jhon1282** [comment]
![Screenshot_2023-03-14-12-00-22-595_com google android youtube](https://user-images.githubusercontent.com/125223735/224981420-7054864d-709f-4144-a020-cb5799041dea.jpg)
Official version

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.164.32](https://github.com/inotia00/revanced-patches/releases/tag/v2.164.32)

**Comment by madhurvarshney** [comment]
The captions are still shown at top.
Youtube v18.09.39
Patch v2.165.1
![Screenshot_2023-03-15-10-53-28-85_d11ae654701a5fadb313ea6fa9a6836f](https://user-images.githubusercontent.com/125809686/225215564-08f10823-39b5-4a50-b28c-c3cd23802839.jpg)

**Comment by inotia00** [comment]
There is no valid fix for this

However, I made it possible to prevent this issue through a switch in the settings

In previous releases, it was not even possible to prevent via a switch.
