### ISSUE TITLE
bug: can't select captions in shorts with hide auto captions - ON.

### ISSUE THREAD

**Issue by kyan5221** [inotia00/ReVanced_Extended#484]
### Type

Error at runtime

### Application

v18.09.39 + v2.164.32 patches

### Bug description

can't select and play captions when I enable hide auti captions.

### Steps to reproduce

1. enable hide auto captions
2. play shorts video which has captions
3. try to select or change captions.

### Relevant log output

```shell
no logs
```

### Screenshots or videos

![20230315_004113](https://user-images.githubusercontent.com/9549962/225067604-725ee4dc-6593-4d0e-9578-7f8c0f80adbe.jpg)

### Device Environment

android 13
samsung oneui 5.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
fixed in revanced-patches-v2.165.1

**Comment by kyan5221** [comment]
> fixed in revanced-patches-v2.165.1

not fixed yet in v2.165.1.

all languages are checked as V and I can't change language.
it displays 'subtitle turned off message' only and not showing subtitle.


![KakaoTalk_20230315_121826558](https://user-images.githubusercontent.com/9549962/225196988-52e89689-a175-48c6-8b69-4c9ee7a76edc.jpg)
![KakaoTalk_20230315_121826558_01](https://user-images.githubusercontent.com/9549962/225196998-cda4abc7-3a0c-46c5-a0e1-975e17e06aa5.jpg)
![KakaoTalk_20230315_121826558_02](https://user-images.githubusercontent.com/9549962/225197009-d84813ef-cf94-4203-b6d3-d39372429d86.jpg)
![KakaoTalk_20230315_121826558_03](https://user-images.githubusercontent.com/9549962/225197018-845dc2bf-55bd-4f56-b30d-40cbf68a5352.jpg)
![KakaoTalk_20230315_121826558_04](https://user-images.githubusercontent.com/9549962/225197022-8cb7edbe-941a-41ca-a253-bf0524654b3d.jpg)

**Comment by inotia00** [comment]
ahh i misunderstood

That setting is a setting in `Player settings`

So.. do not hide or disable any component in Shorts Player.

So it's normal that it doesn't work

A patch to turn off subtitles in Shorts Player has not been implemented

**Comment by inotia00** [comment]
However.. since this is a valid bug, I will reopen the issue.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.166.8](https://github.com/inotia00/revanced-patches/releases/tag/v2.166.8)

**Comment by kyan5221** [comment]
> fixed in [revanced-patches-v2.166.8](https://github.com/inotia00/revanced-patches/releases/tag/v2.166.8)

is 'hide-auto-caption' only for normal video? not for shorts?

my issue is that caption in shorts are displayed automatically even I enabled 'hide-auto-caption'.
is it normal in RVX?

**Comment by inotia00** [comment]
iirc, I changed it to only apply to normal videos, as I can't fix the issue in Shorts.

If you are willing to provide additional context, please provide the following information:

1. Please provide the URL of the video with forced auto captions in Shorts.
2. Please check if this issue is reproduced in the official ReVanced.

**Comment by kyan5221** [comment]
> Updated: I found Shorts with forced auto captions, and I tested it on ReVanced and RVX, respectively.
> 
> Video url: https://youtube.com/shorts/BB5HDvgPb3E
> 
> When `Disable forced auto captions` is turned on, the results of Revanced and RVX are as follows.
> 
> ![result](https://private-user-images.githubusercontent.com/108592928/297002509-6308d101-9b7c-45a8-8cbb-bae6b6f54c25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzOTg5OTksIm5iZiI6MTcwNTM5ODY5OSwicGF0aCI6Ii8xMDg1OTI5MjgvMjk3MDAyNTA5LTYzMDhkMTAxLTliN2MtNDVhOC04Y2JiLWJhZTZiNmY1NGMyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQwOTUxMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lN2NlNGQ2MTU2MjY5Y2JjMWUwNWExMDg2N2JkNTA3OTlhMGM3YTFhMjMzOWQ0ZmRjYzA1MzcwMTVhYjk0YTRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MYhYrAggCADd-c5wYnb444FHV9JNE63l3g8fsab6t68)
> 
> Stock YouTube: `Forced auto captions` is applied Revanced: `Disable forced auto captions` works, but still has [issue](https://github.com/inotia00/ReVanced_Extended/issues/484). RVX: `Disable forced auto captions` works, [issue](https://github.com/inotia00/ReVanced_Extended/issues/484) has been resolved.
> 
> Probably, if you still have this [issue](https://github.com/inotia00/ReVanced_Extended/issues/1915), simply apply the patch again.
> 
> In [revanced-patches-v2.209.1](https://github.com/inotia00/revanced-patches/releases/tag/v2.209.1), `Disable forced auto captions` will also be applied in Shorts.

in most case, captions are turned off automatically in shorts. but sometimes (scroll up shorts videos) it doesn't block captions and displays captions. 
so I have to select 'turn off captions' manually in shorts.

**Comment by inotia00** [comment]
Please let me know the version of revanced-patches

**Comment by kyan5221** [comment]
> Please let me know the version of revanced-patches

![Screenshot_20240116_192054_YouTube](https://github.com/inotia00/ReVanced_Extended/assets/9549962/71ce8f3c-4df4-46ff-85c4-5b1f870c4fd2)

**Comment by inotia00** [comment]
If so, this is a bug.

It is impossible to fix it because it cannot be reproduced on my side, but I will reopen the [previously opened issue](https://github.com/inotia00/ReVanced_Extended/issues/1915) for other users who visit with the same issue.

**Comment by kyan5221** [comment]
> If so, this is a bug.
> 
> It is impossible to fix it because it cannot be reproduced on my side, but I will reopen the [previously opened issue](https://github.com/inotia00/ReVanced_Extended/issues/1915) for other users who visit with the same issue.

I found how to reproduce it.

1. enable 'Disable forced auto captions ' in RVX settings.
2. play one video and click <CC> overlay button to turn on caption and watch it with caption.
3. watch other videos.
4. select shorts in nav bar and play shorts videos which has 'forced auto captions'.
5. shorts player will display caption in this case.

is it a bug or normal?

**Comment by inotia00** [comment]
If so, this is not a bug

`Disable force auto captions` setting prevents captions from being applied to videos where auto captions are forced

As a representative example, auto captions are forced when the following Shorts are opened on an stock YouTube or in a web browser

https://youtube.com/shorts/BB5HDvgPb3E

`Disable force auto captions` setting makes prevent this

It is not a feature that disables remembering captions that the user previously changed

If you use official ReVanced, you can disable remembering captions in Shorts, but this will make it impossible for users to enable captions in Shorts
