### ISSUE TITLE
bug: `optimize-resource` patch removes license activity

### ISSUE THREAD

**Issue by BrilliantlyEducated** [inotia00/ReVanced_Extended#568]
### Type

Error at runtime

### Application

version 18.11.36

### Bug description

it causes the app to crash

### Steps to reproduce

go to Settings > About  > Open source licenses

### Relevant log output

```shell
.
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.166.18](https://github.com/inotia00/revanced-patches/releases/tag/v2.166.18)

**Comment by inotia00** [comment]
not reproduced
Check if v2.166.18 is properly marked in the patch information.

**Comment by madhurvarshney** [comment]
Oh, my bad. It is still on patch v2.166.15
I patch using ReVanced Manager and it still shows v2.166.15 as latest patch. Why?
![Screenshot_2023-03-27-22-26-12-06_a85b47aaa863e3bc831e16d29c27a79c](https://user-images.githubusercontent.com/125809686/228012279-16f70996-1a65-45bb-8eb0-0a9878d688b0.jpg)

Also, the second thing I noticed regarding ReVanced Manager is that it shows "Manager: Loading..." in the update section. Is there something going wrong with it currently?
![Screenshot_2023-03-27-22-25-18-59_a85b47aaa863e3bc831e16d29c27a79c](https://user-images.githubusercontent.com/125809686/228012748-b4f57ff7-eca8-40d3-a11f-724f22988112.jpg)

**Comment by inotia00** [comment]
I'm not a maintainer of ReVanced Manager either, so I don't know why
Perhaps, it is assumed that there is a slight delay in receiving the API from the server.

Try patching again tomorrow

**Comment by madhurvarshney** [comment]
Okay, thanks for clarification!

**Comment by Neophytae** [comment]
Sometimes, clearing revanced manager app data will cause it to load the latest changes
