### ISSUE TITLE
bug: video ad whitelist not working

### ISSUE THREAD

**Issue by rsaurav12** [inotia00/ReVanced_Extended#647]
### Type

Other

### Application

YouTube : 18.12.35
Patches: 2.168.12

### Bug description

After Whitelisted any channel for ads or/and sponsorblock, the ads and sponsors still won't show up on that channel

### Steps to reproduce

1) include "overlay-button" patch and  patch it  and then install
2) go to "overlay button " section in Revanced settings
3) enable "show whitelist button"
4) go to your desire channel that you wanna watchlist it
5) click any video of than channel
6) tap on Whitelist button on video overlay
7) tap on ADS and SB button
8) try to watch the same video again or another video of that same channel you watchlisted
9) you will see ads are still not showing up and sponsor still are getting blocked 

### Relevant log output

```shell
No log
```

### Device Environment

MIUI 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.168.15](https://github.com/inotia00/revanced-patches/releases/tag/v2.168.15)

**Comment by rsaurav12** [comment]
Thanks 👍 but you didn't fix video ads whitelist not working 😅 i needed it more than sponsorblock whitelist

**Comment by inotia00** [comment]
bruh.. Even though the video ad whitelist didn't work since November last year, I didn't know until now because no one reported it.

Anyway, I will change the title and reopen

**Comment by inotia00** [comment]
ahh you already opened an issue I'll close it again

**Comment by rsaurav12** [comment]
Thank bro and sorry for the trouble 🙇
