### ISSUE TITLE
bug: dislikes count overridden when playing Shorts using PIP

### ISSUE THREAD

**Issue by jhon1282** [inotia00/ReVanced_Extended#673]
### Type

Other

### Application

Youtube 18.12.35

### Bug description

The dislike count of a video is shown equal to that of the last short watched if you exit and re-enter the application without closing both.

### Steps to reproduce

Start video
Watch the Dislikes
Now launch Short
Watch the Dislikes
Close app
Re-open and go back to the initial video
Both have the same number of Dislikes

### Relevant log output

```shell
N
```

### Screenshots or videos

https://user-images.githubusercontent.com/125223735/230723602-b3a22594-8aae-47ad-92f7-15a7b4332663.mp4

![IMG_20230408_065344](https://user-images.githubusercontent.com/125223735/230720962-58fa2b50-43b2-4bb7-9b78-a85f06f03060.jpg)
![IMG_20230408_063602](https://user-images.githubusercontent.com/125223735/230720980-9dfa6a8b-dd9c-443b-b435-1102153d037e.jpg)
![IMG_20230408_063313](https://user-images.githubusercontent.com/125223735/230720994-ad0b686b-5cfa-42ac-9ec8-6b1b9451ebc1.jpg)

### Device Environment

Android 11. MIUI 12.5 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
fixed in [revanced-patches-v2.168.24](https://github.com/inotia00/revanced-patches/releases/tag/v2.168.24)

**Comment by jhon1282** [comment]
Thank you for your hard work but I have the same bug after new Patches too.

**Comment by madhurvarshney** [comment]
Yes, this bug is still there after applying the latest patch (v2.168.27).

**Comment by inotia00** [comment]
nah.. if you patched correctly with revanced-patches-v2.168.27, then this issue can never happen because issue: '[dislikes disappear when you watch related shorts](https://github.com/inotia00/ReVanced_Extended/issues/668)' is still there

![v](https://user-images.githubusercontent.com/108592928/230778013-57b4146a-0a1f-4b8b-95cd-7129e14716b1.png)
Check that the correct version is shown in the patch information

**Comment by jhon1282** [comment]
Yes I patched with Revancify, but the bug for some reason remained

![Screenshot_2023-04-09-16-23-29-449_app rvx android youtubf](https://user-images.githubusercontent.com/125223735/230778590-f479d485-17d6-412d-a9ed-2b28ce4d540e.jpg)

**Comment by madhurvarshney** [comment]
Yes, I too have checked the version. It is v.2.168.27 and the issue still persists.
![Screenshot_2023-04-09-20-35-15-64_d11ae654701a5fadb313ea6fa9a6836f](https://user-images.githubusercontent.com/125809686/230780644-3b3c2402-def9-4432-bb5c-68c1821da62a.jpg)

**Comment by jhon1282** [comment]
Always remember the Dislikes of the last short watched, my impression is that going back in reality the short remains running in the background.
It's possible?

**Comment by madhurvarshney** [comment]
Hey @inotia00, ig this issue should be reopened as it still persists. Right?

**Comment by inotia00** [comment]
not reproduced on my side

Also, the 'dislikes disappear when you watch related shorts' issue and this issue cannot occur at the same time.

**Comment by madhurvarshney** [comment]
The steps to reproduce this issue are different from that of 'dislikes disappear when you watch related shorts' issue.
To reproduce this issue you need to close the app (by pressing home button) while watching shorts and then reopen the app. (See the video attached for the illustration of the steps to be followed)

While for the 'dislikes disappear when you watch related shorts' issue, you don't need to close the app. You just have to press back while watching shorts.

Follow the steps shown in the video below:

https://user-images.githubusercontent.com/125809686/231138558-e97f7631-f54b-41ad-ab38-0cea0f0193f5.mp4

This issue occurs irrespective of the PIP mode ON/OFF.

**Comment by inotia00** [comment]
got it
When this issue was first opened, it was not reproducible with the method provided.

However, it was reproducible when **PIP mode was enabled** in YouTube settings.

※ This issue is reproduced in official ReVanced as well.

**Comment by madhurvarshney** [comment]
Just to add, even if I disable PIP mode in settings, the issue is still there. See the video below:

https://user-images.githubusercontent.com/125809686/231173649-5e6f7541-cd4a-4537-b0a3-ee1ce8289ebc.mp4

**Comment by jhon1282** [comment]
That's right, but it has been since I opened the first time it is.
You see from the first video, I never mentioned the pip, I probably explained myself badly.

**Comment by inotia00** [comment]
fixed in revanced-patches-v2.168.33

**Comment by madhurvarshney** [comment]
Still not fixed.

**Comment by inotia00** [comment]
Unfortunately, there will be no further fixes

**Comment by madhurvarshney** [comment]
No problem. After all, it's a very minor issue that can be easily neglected. Appreciate your work and time! ❤️
