### ISSUE TITLE
question: Crowdin Translations Suspended?

### ISSUE THREAD

**Issue by giwrgosmant** [inotia00/ReVanced_Extended#87]
### Application

Other

### Description

Hi again @inotia00, I started translating ReVanced Extended in Crowdin few days ago, now I go to continue but it's say it's suspended.
![2023-01-02 12_11_36-Crowdin](https://user-images.githubusercontent.com/51835189/210217813-d44b8b8d-b0f7-4843-9530-3bf0f6c62255.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by inotia00** [comment]
The project is not closed by me
I have submitted an open source conversion request to Crowdin

refer this guide temporarily
https://telegra.ph/How-to-contribute-to-Crowdin-translations-via-upload-of-stringsxml-file-11-10

**Comment by giwrgosmant** [comment]
> 

I see, yeah I remember that guide, I will bring it back on my thread too. However it will be much harder to translate all these manually.
**If** the problem with Crowdin continues, do you mind to change Translation platform like Weblate or Transifex etc.?

**Comment by inotia00** [comment]
I also thought about moving to another platform, but it was not as intuitive and convenient as Crowdin, so I couldn't completely transfer it.

However, if this issue persists, I think I should consider migrating to a completely independent open source localization platform.

**Comment by giwrgosmant** [comment]
> I also thought about moving to another platform, but it was not as intuitive and convenient as Crowdin, so I couldn't completely transfer it.
> 
> However, if this issue persists, I think I should consider migrating to a completely independent open source localization platform.

I totally agree.  Let's see how it will goes in the following days if not solve, it would be better to move to another platform.
Thanks for the information. Cheers!

**Comment by giwrgosmant** [comment]
@inotia00 as the days and the updates move on, it's hard to track the changes in Crowdin with the current situation Download/Upload.

I see you did some recent changes and restored translations but for example now Greek translation says 97%. It's hard to track the strings which need translation without having access to Crowdin platform itself to translate via it.

I think it's time to move to Weblate or Transifex or somewhere else so it would be easy for everyone to contribute, unless they fix this "suspension" soon (it's been already long time).

Btw u are on fire these days. Update after update everyday I can't stop building 😋

**Comment by inotia00** [comment]
Translation resources for European countries have been moved to the following page:
https://crowdin.com/project/revancedextendedeu

**Comment by giwrgosmant** [comment]
> Translation resources for European countries have been moved to the following page: https://crowdin.com/project/revancedextendedeu

Thanks mate, that worked. I have completed 100% the Greek language. If you can give me proofreader also there. [Crowdin profile](https://crowdin.com/profile/Retrial).
I will take a full look with the time to correct possible mistakes in the Translation.

Thanks again.

**Comment by inotia00** [comment]
done

**Comment by giwrgosmant** [comment]
> done

Hi, thanks, I got it on Music but I still don't have it on EU project.

**Comment by inotia00** [comment]
Total number of words in the music project is only 8000, so I didn't separate the project

**Comment by giwrgosmant** [comment]
> Total number of words in the music project is only 8000, so I didn't separate the project

I mean you made me Proofreader on YouTube Extended project also before but when u separated the Project on EU I am no longer there.

**Comment by cuynu** [comment]
> > Total number of words in the music project is only 8000, so I didn't separate the project
> 
> I mean you made me Proofreader on YouTube Extended project also before but when u separated the [Project on EU](https://crowdin.com/profile/ReVanced_Extended_EU) I am no longer there.

He will busy until june

**Comment by giwrgosmant** [comment]
> > > Total number of words in the music project is only 8000, so I didn't separate the project
> > 
> > 
> > I mean you made me Proofreader on YouTube Extended project also before but when u separated the [Project on EU](https://crowdin.com/profile/ReVanced_Extended_EU) I am no longer there.
> 
> He will busy until june

I am already aware about it, but he replied me 3h ago 😛Also I didn't pressured for anything, just he should take a look when he has time.
